### ISSUE TITLE
Align as an enum

### ISSUE THREAD

**Issue by juanmottesi** [unq-ui/arena-kotlin-extensions#3]
It is easier to interact with an enum than with a string.

```kotlin
fun Control.align(position: String): Control =
  when (position.toLowerCase()) {
    "left" -> this.alignLeft()
    "right" -> this.alignRight()
    "center" -> this.alignCenter()
    else -> this.alignLeft()
}
```
Something like

```kotlin
fun Control.align(position: Align): Control =
  when (position) {
    Align.left -> this.alignLeft()
    Align.right -> this.alignRight()
    Align.center -> this.alignCenter()
    else -> this.alignLeft()
}
```

**Comment by laendoor** [comment]
I think it's worst to write for users.

With your propose, you should write like this:

```kt
val label = Label(panel)
label.align(Align.center)
```

But with _string way_, you can code like this:

```kt
val label = Label(panel)
label.align("center")
```

In fact, using infix function, the codes it's something like this

```kt
label align Align.center
label align "center"
```

I know you can import _aligns_, but over the time it becomes very cumbersome.

I thought that the best solution should be using _atoms_/_symbols_, like Erlang or Ruby, (`label.align(:center)`) but Kotlin doesn't have it.
